apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-c2b-consumer.fullname" . }}
  labels:
    {{- include "generic-c2b-consumer.labels" . | nindent 4 }}
  annotations:
    {{- include "generic-c2b-consumer.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-c2b-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-c2b-consumer.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.service.secrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "generic-c2b-consumer.fullname" . }}-secret 
{{- end }}
          env:
  {{- range $key, $value := .Values.extraVars }}
          - name: {{ $key }}
            value: {{ $value }}
  {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP             
          livenessProbe:
            httpGet:
              # path: /actuator/health/liveness
              path: /actuator/health
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              # path: /actuator/health/readiness
              path: /actuator/health
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or ( eq .Release.Namespace "production" ) (eq .Release.Namespace "approval") }}
      tolerations:
        - key: "nodes"
          operator: "Equal"
          value: "{{ .Values.service.nodegroup }}"
          effect: "NoSchedule"
    {{ else }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}

